/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fountain.gltf --transform
Author: guillemvilah (https://sketchfab.com/guillemvilah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/valencia-fountain-0198556e1b6648289693b0bac4fe496d
Title: Valencia Fountain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/fountain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 0, 0, 0]} scale={0}>
        <mesh geometry={nodes.Ground_Ground02_0.geometry} material={materials.Ground02} />
        <mesh geometry={nodes.Ground_Ground01_0.geometry} material={materials.Ground01} />
      </group>
      <group position={[0, 0, 0]} scale={0.00634}>
        <mesh geometry={nodes.ValenciaFountain_FountainDifuse_0.geometry} material={materials.FountainDifuse} />
        <mesh geometry={nodes.ValenciaFountain_FountainTrans_0.geometry} material={materials.FountainTrans} />
      </group>
      <mesh geometry={nodes.Water_Water_0.geometry} material={materials.Water} position={[0, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/fountain-transformed.glb')
